table 'BlinkIT Grocery Data'
	lineageTag: 48168e8f-1384-4342-8052-93455387a866

	measure 'total sales' = SUM('BlinkIT Grocery Data'[Sales])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 00258d70-8123-4b8d-b392-d0789cd15a5c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Avarage sales' = AVERAGE('BlinkIT Grocery Data'[Sales])
		lineageTag: cc271f1f-d617-474c-8f41-466f8d57f127

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avaerage rating' = AVERAGE('BlinkIT Grocery Data'[Rating])
		lineageTag: d243bcb1-bbdc-4ccb-9693-9a7a828c57c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No of items' = COUNTROWS('BlinkIT Grocery Data')
		formatString: 0
		lineageTag: 5eecb048-96f2-46d2-b7a6-cb80237ed25f

	column 'Item Fat Content'
		dataType: string
		lineageTag: bfa14631-04f4-4b6d-a892-41f9f615bb31
		summarizeBy: none
		sourceColumn: Item Fat Content

		annotation SummarizationSetBy = Automatic

	column 'Item Identifier'
		dataType: string
		lineageTag: c979da4e-8fca-4d30-94c6-e2bd1057de7a
		summarizeBy: none
		sourceColumn: Item Identifier

		annotation SummarizationSetBy = Automatic

	column 'Item Type'
		dataType: string
		lineageTag: d909f0af-7dd7-44a9-86ec-a3f03470796a
		summarizeBy: none
		sourceColumn: Item Type

		annotation SummarizationSetBy = Automatic

	column 'Outlet Establishment Year'
		dataType: int64
		formatString: 0
		lineageTag: 235127d8-27b7-4964-aaf2-b1bac9b7b4f4
		summarizeBy: none
		sourceColumn: Outlet Establishment Year

		annotation SummarizationSetBy = Automatic

	column 'Outlet Identifier'
		dataType: string
		lineageTag: 09b8a4d3-ced7-49bb-bc5f-cac1b94cf75d
		summarizeBy: none
		sourceColumn: Outlet Identifier

		annotation SummarizationSetBy = Automatic

	column 'Outlet Location Type'
		dataType: string
		lineageTag: d8eb3b50-10be-43fe-b3f4-beb90361c14e
		summarizeBy: none
		sourceColumn: Outlet Location Type

		annotation SummarizationSetBy = Automatic

	column 'Outlet Size'
		dataType: string
		lineageTag: f97f6a8e-3cf5-4683-9a74-56426232cb4a
		summarizeBy: none
		sourceColumn: Outlet Size

		annotation SummarizationSetBy = Automatic

	column 'Outlet Type'
		dataType: string
		lineageTag: be186611-e865-40a4-875c-988515ca2129
		summarizeBy: none
		sourceColumn: Outlet Type

		annotation SummarizationSetBy = Automatic

	column 'Item Visibility'
		dataType: double
		lineageTag: 406d0f77-bf0f-4159-a580-21d14609117e
		summarizeBy: none
		sourceColumn: Item Visibility

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Item Weight'
		dataType: double
		lineageTag: dbc2d54e-12ac-4dc2-9f3a-ac1f7fff301f
		summarizeBy: none
		sourceColumn: Item Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: 1a4ef5b7-c287-438d-a27a-1452c34de881
		summarizeBy: none
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Rating
		dataType: int64
		formatString: 0
		lineageTag: e272254d-7454-4ed0-a71b-5a96630d30d5
		summarizeBy: none
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

	partition 'BlinkIT Grocery Data' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\puja\Downloads\BlinkIT Grocery Data.xlsx"), null, true),
				    #"BlinkIT Grocery Data_Sheet" = Source{[Item="BlinkIT Grocery Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"BlinkIT Grocery Data_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Item Fat Content", type text}, {"Item Identifier", type text}, {"Item Type", type text}, {"Outlet Establishment Year", Int64.Type}, {"Outlet Identifier", type text}, {"Outlet Location Type", type text}, {"Outlet Size", type text}, {"Outlet Type", type text}, {"Item Visibility", type number}, {"Item Weight", type number}, {"Sales", type number}, {"Rating", Int64.Type}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"Item Identifier"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each [Item Identifier] <> null and [Item Identifier] <> ""),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Filtered Rows", {"Item Identifier"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Errors", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Blank Rows"),
				    #"Removed Errors1" = Table.RemoveRowsWithErrors(#"Removed Duplicates1", {"Item Fat Content", "Item Identifier", "Item Type", "Outlet Establishment Year", "Outlet Identifier", "Outlet Location Type", "Outlet Size", "Outlet Type", "Item Visibility", "Item Weight", "Sales", "Rating"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Errors1","LF","Low fat",Replacer.ReplaceText,{"Item Fat Content"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Reg","Regular",Replacer.ReplaceText,{"Item Fat Content"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Regularular","Regular",Replacer.ReplaceText,{"Item Fat Content"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value2", each [Item Weight] <> null and [Item Weight] <> "")
				in
				    #"Filtered Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

